### ISSUE TITLE
Documentation referencing 'react-native-view'

### ISSUE THREAD

**Issue by LaszloDev** [hyrwork/react-native-row#11]
`import Row, { View as DialView } from 'react-native-view'` should be 
`import Row, { View as DialView } from 'react-native-row'` <- 'row'

**Comment by ssomnoremac** [comment]
Thanks, updated. As a note, this repo is not production ready. There really needs to be a caching solution. I've been spending my few front-end OS hours on the glamorous-native project which I hope to add as a dependency here at some point.
