### ISSUE TITLE
Add backgroundColor prop

### ISSUE THREAD

**Issue by ssomnoremac** [hyrwork/react-native-row#2]
Pros:

- according my [my own study](https://medium.com/@fasterpancakes/styles-in-react-native-a-case-study-3dbe0d50f308#.jhk1v2dic) this is the most common style used.
- would be easy to add

Cons:

- Would be the first prop on RN-row to address a style style rather than a layout style
- Could add bloat to the instance of Row/View unless perhaps we shortened the prop name
- bgColor, color, bg, background, we'd have to pick one of those rather than backgroundColor in my opinion

**Comment by ssomnoremac** [comment]
#3

**Comment by tacomanator** [comment]
IMO you'd be better off keeping this library very focused on layout related concerns.

**Comment by ssomnoremac** [comment]
@tacomanator , I agree, thanks. I'll leave the branch just because it saves me hundreds of lines of style definitions.
