### ISSUE TITLE
Resolve conflicts with layout props

### ISSUE THREAD

**Issue by ssomnoremac** [hyrwork/react-native-row#6]
I was completely unaware that you could set layout props directly on the component instead of in style

    <View backgroundColor="red"/>

is the same as:

    <View styles={{backgroundColor: "red"}}/>

at least as far as I can tell. So `margin={0}` is already implemented and this library doesn't need to address that. But what's interesting is this fails:

    position={[23,13]} 

but  

    margin={[34,23]} 

does not. I'm going to look at why, because I think I had position working at one point. Are there any other conflicts we should worry about?

**Comment by ssomnoremac** [comment]
looks like flex is actually accounted for completely. Somehow the flex boolean works. A `true` is interpreted as `flex:1` so I've removed flex completely from this library. As for position, I'm just going to go with `pos` for now.

**Comment by eightyfive** [comment]
Just a note to mention that Layout props cannot be set on [react-native-web](https://github.com/necolas/react-native-web) `View` component.

And according to the creator:
> ... this was an early accident in React Native.

https://github.com/necolas/react-native-web/issues/914
